/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Todo;

import view.MainScreen;

public class App {    

    public static void main(String[] args) {
        
        new MainScreen().setVisible(true);

    }
}
